services:
  backend:
    build:
      context: ./python-backend  # Caminho correto para o backend
      dockerfile: Dockerfile
    container_name: backend_app
    working_dir: /app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./python-backend:/app
    env_file:
      - .env
    restart: always 

  db:
    image: postgres:17
    container_name: apicela_db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./data_import:/data_import
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    env_file:
      - .env

  frontend:
    build:
      context: ./apicela-frontend  # Caminho correto para o frontend
      dockerfile: Dockerfile
    container_name: vue_frontend
    ports:
      - "8080:8080"
    volumes:
      - ./apicela-frontend:/app
      - /app/node_modules  # Evita conflitos de dependências
    depends_on:
      - backend
    environment:
      - VITE_API_BASE_URL=http://backend:8000
