version: "3.8"

services:
  app:
    build: .
    container_name: app
    working_dir: /app  # Define o diretório de trabalho dentro do container .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./app:/app
    env_file:
      - .env
    restart: always 


  db:
    image: postgres:17
    container_name: apicela_db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./data_import:/data_import
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    env_file:
      - .env